name: Nopeus
description: >
  Adds an application layer to the cloud.
author: Elon Salfati (Salfati Group)
inputs:
  release_version:
    description: Override the nopeus.yaml release images
    required: false
  environments:
    description: A list of the environments to deploy frmo the nopeus file. Optional, by default deployes all the environments. e.g., prod,staging
    required: false
  aws_access_key_id:
    description: The AWS access key id
    required: false
  aws_secret_access_key:
    description: The AWS secret access key
    required: false
  ignore_env_files:
    description: Ignore the .env file reference in the nopeus.yaml
    required: false
    default: "false"
runs:
  using: node16
  main: dist/index.js
