name: Nopeus
description: >
  Adds an application layer to the cloud.
author: Elon Salfati (Salfati Group)
inputs:
  release_version:
    description: Override the nopeus.yaml release images
    required: false
  disable_cache:
    description: Disable the remote cache for the nopeus.yaml
    required: false
  aws_access_key_id:
    description: The AWS access key id
    required: false
  aws_secret_access_key:
    description: The AWS secret access key
    required: false
runs:
  using: node16
  main: dist/index.js
